## This file is a template remove the .template to use the file

libraries:
  Anime:
    remove_overlays: false
    collection_files:
    - config/anime/anime-franchise.yml
    - config/anime/anime-studios.yml
    - config/anime/anime.yml
  Movies:
    remove_overlays: false
    overlay_files:
    - file: config/overlays/jmxd/gradient.yml   #Top Gradient
    - default: resolution   #Resolution & Dynamic Range
      template_variables:
        file: config/overlays/jmxd/resolution/<<key>><<alt>>.png
        use_resolution: true
        use_edition: false
        horizontal_offset: 50
        horizontal_align: left
        vertical_offset: 50
        vertical_align: top
        back_radius: 0
        back_align: left
        back_color: '#00000000'
        back_height: 50
    - default: audio_codec   #Audio Codec
      template_variables:
        file: config/overlays/jmxd/audio_codec/<<key>>.png
        horizontal_offset: 50
        horizontal_align: right
        vertical_offset: 50
        vertical_align: top
        back_radius: 0
        back_align: right
        back_color: '#00000000'
        back_height: 50
    - default: resolution   #Edition
      template_variables:
        file: config/overlays/jmxd/edition/<<key>>.png
        use_resolution: false
        use_edition: true
        horizontal_offset: 0
        horizontal_align: center
        vertical_offset: 0
        vertical_align: bottom
        back_radius: 0
        back_color: '#00000000'
        back_height: 153
    collection_files:
    - config/movies/movies-decades.yml
    - config/movies/movies-studios.yml
    - config/movies/movies.yml
  Stand-up:
    remove_overlays: false
    overlay_files:
    - file: config/overlays/jmxd/gradient.yml   #Top Gradient
    - default: resolution   #Resolution & Dynamic Range
      template_variables:
        file: config/overlays/jmxd/resolution/<<key>><<alt>>.png
        use_resolution: true
        use_edition: false
        horizontal_offset: 50
        horizontal_align: left
        vertical_offset: 50
        vertical_align: top
        back_radius: 0
        back_align: left
        back_color: '#00000000'
        back_height: 50
    - default: audio_codec   #Audio Codec
      template_variables:
        file: config/overlays/jmxd/audio_codec/<<key>>.png
        horizontal_offset: 50
        horizontal_align: right
        vertical_offset: 50
        vertical_align: top
        back_radius: 0
        back_align: right
        back_color: '#00000000'
        back_height: 50
  TV Shows:
    remove_overlays: false
    overlay_files:
    - default: network              # TV Show Networks
      template_variables:
        vertical_align: bottom
        vertical_offset: 15
        horizontal_align: left
        horizontal_offset: 15
    collection_files:
    - config/tv/tv-networks.yml

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order: 8
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids: []
  ignore_imdb_ids: []
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users: []
  playlist_report: false
  verify_ssl: true
  custom_repo: ''
  check_nightly: true
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
  show_unfiltered: false
webhooks:
  error: notifiarr
  version: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
  delete:
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192-168-4-193.addis-nas.direct.quickconnect.to:32400/
  token: <<plexkey>>
  timeout: 60
  db_cache: ''
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:
tmdb: # REQUIRED for the script to run
  apikey: <<tmdbkey>>
  language: en
  cache_expiration: 60
  region:
github:
  token: <<githubkey>>
notifiarr:
  apikey: <<notifiarrkey>>
