# Anime Studio Collections
templates:
  company:
    tmdb_company: <<company_id>>
    collection_order: release.asc
    sync_mode: sync
    sort_title: "!C <<collection_name>>"

collections:
  A-1 Pictures:
    template: { name: company, company_id: 13113 }
  Bones:
    template: { name: company, company_id: 2849 }
  CloverWorks:
    template: { name: company, company_id: 121589 }
  Deen Studio: 
    template: { name: company, company_id: 6075 }
  Gonzo:
    template: { name: company, company_id: 1077 }
  Lerche: 
    template: { name: company, company_id: 42811 }
  Liden Films:  
    template: { name: company, company_id: 42521 }
  J.C. Staff:
    template: { name: company, company_id: 11884 }
  Kyoto Animation:
    template: { name: company, company_id: 5438 }
  Madhouse:
    template: { name: company, company_id: 3464 }
  MAPPA:
    template: { name: company, company_id: 21444 }
  Pierrot:
    template: { name: company, company_id: 3234 }
  Production I.G:
    template: { name: company, company_id: 529 }
  Sunrise:
    template: { name: company, company_id: 3153 }
  TMS Entertainment:
    template: { name: company, company_id: 7164 }
  Toei Animation:
    template: { name: company, company_id: 5542 }
  Trigger:
    template: { name: company, company_id: 50908 }
  Ufotable:
    template: { name: company, company_id: 5887 }
  Xebec:
    template: { name: company, company_id: 5937 }    
  White Fox:
    template: { name: company, company_id: 12569 }
  Wit Studio:
    template: { name: company, company_id: 31058 }
